# Generated by Django 4.2.3 on 2023-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_email_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
